# Generated by Django 3.2.8 on 2021-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasMaisAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('divisao', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carencia', models.PositiveIntegerField(default=0)),
                ('taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
