# Generated by Django 3.2.8 on 2021-10-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PronafMaisAlimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasmaisalimentos',
            name='resultado',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
