# Generated by Django 3.2.8 on 2021-10-28 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PronafMaisAlimentos', '0004_auto_20211024_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasmaisalimentos',
            name='dataPrimeiraParcela',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 19, 54, 56, 743927)),
        ),
    ]
